version: '3.3'
services:
  aha_mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db_ahainclusion'
      MYSQL_USER: 'ahabackend'
      MYSQL_PASSWORD: 'grupo1aha'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ahainclusion-db:/var/lib/mysql
volumes:
  ahainclusion-db: